### ISSUE TITLE
Problem with conflicting options (version, unattended)

### ISSUE THREAD

**Issue by plequang** [aerobatic/yoke-cli#1]
Hi,

I think there is an issue with the version option in yoke cli. It conflicts with the version function of commander.

For example in deploy.js, the following line of code fails because program.version is a function

```javascript
var versionNameError = validateVersionName(program.version);
```

(https://github.com/aerobatic/yoke-cli/blob/master/commands/deploy.js#L153).

Also, -u option is used for both userId and unattended, so if I type
```
yoke -u deploy
```
It parses deploy as the userId.

**Comment by dvonlehman** [comment]
Excellent catch. I have renamed the version option to "-n, --name" and the unattended option to "-x, --unattended" to avoid these conflicts. This was published to npm as 0.0.21.

**Comment by plequang** [comment]
Unfortunately, 'name' is also conflicting with the 'name' function of commander (which returns the name of the command, here 'yoke').

**Comment by dvonlehman** [comment]
You are correct. The commander api is odd in that it extends the root `program` object directly with the arbitrary option names. I am now using the more explicit `--version-name` without a corresponding short flag.
