### ISSUE TITLE
Issues with serve/sim when trying to kill running process

### ISSUE THREAD

**Issue by plequang** [aerobatic/yoke-cli#2]
Hi,

This relates only to using yoke on windows. I've not tried on linux/mac.

The killPortProcessess function of serve.js uses a node module called process-finder (https://github.com/bevacqua/process-finder). This modules uses 'grep' which is not directly available on windows. 

I've submitted an issue to process-finder author (https://github.com/bevacqua/process-finder/issues/1), so maybe you will want to follow if there will be an update to this module.

Also, another issue with killPortProcesses is related to process.kill. As described in node.js documentation, process.kill is just sending a signal, and you cannot expect the process to be terminated immediatly. This is what happened on my machine when I've run `yoke sim` twice. The second instance failed, because the first instances processes are not terminated yet.

This is not a blocking issue as I don't usually start yoke twice at the same time.

The first problem is more blocking.

Thanks
Pascal

**Comment by dvonlehman** [comment]
I determined that the best solution for the time being is to eliminate the dependency on process-finder and not attempt to programmatically kill any running yoke processes. Developers can send their own SIGTERM to kill any running instances of yoke, which they are likely accustomed to doing if they've done any node programming and received the "port in use" error. Will revisit down the road to determine if there is a more elegant error handling technique to display a friendly error. This fix is available on npm in version 0.0.22.
