### ISSUE TITLE
--force option not implemented in deploy command

### ISSUE THREAD

**Issue by plequang** [aerobatic/yoke-cli#4]
(Continuing on migrating from grunt-aerobatic to yoke for a CI build.)

Even though documented here http://www.aerobatic.com/docs/yoke, the --force option is not implemented in yoke.js

Something like 
```
  .option('-f, --force', 'Immedietely direct all production traffic to this new version')
```

is missing around line 62 in yoke.js

**Comment by dvonlehman** [comment]
Exactly so.

**Comment by plequang** [comment]
Thanks a lot. Everything is working now.

**Comment by dvonlehman** [comment]
That's great to hear! Please continue to let us know if there are bugs or
anything blocking your path forward.

David
