### ISSUE TITLE
yoke create-app is not working on windows

### ISSUE THREAD

**Issue by plequang** [aerobatic/yoke-cli#5]
Hi,

The command
```
yokei create-app 
```
is not working on windows.

It fails when running ```spawn('npm', ['install'])```
Actually this is because of this node.js issue : https://github.com/joyent/node/issues/2318
```spawn``` does not find ```npm.cmd``` on windows.
The same problem occurs when running bower.

Unfortunately, I don't have the impression that this is about to be solved in node.

Personnally, I've modified yoke-cli locally to run ```npm.cmd```  and ```bower.cmd``` so that it works.

**Comment by bharrison1984** [comment]
Any details on how you accomplished this, I'm having the same problem

**Comment by dvonlehman** [comment]
Hi, the latest version of yoke-cli on npm includes a windows specific patch to address the joyent/node#2318 issue.  It's based on the solution used in the [spawn-cmd](https://github.com/featurist/spawn-cmd/blob/master/spawn.js) module. Please `npm update -g yoke-cli` and give it a shot. Thanks.

**Comment by plequang** [comment]
Hi David,

Just tested create-app with yoke-cli 1.0.5 and it works on windows now.
So I'm closing this issue.
Thanks

Pascal

**Comment by ghost** [comment]
Ok, my problem was unrelated to the previous issue. It seems that I only have the problem when trying to run 'yoke create-app' on a Windows 8 PC, with a Microsoft Live account instead of a local account. I created a new local profile, and boom everything seemed to work fine.

**Comment by plequang** [comment]
That's strange. I'm also using a windows 8 PC, signed in with a microsoft account, and `yoke create-app` is working for me,

What kind of error do you get ?
