### ISSUE TITLE
Deploying html files removes empty attributes

### ISSUE THREAD

**Issue by plequang** [aerobatic/yoke-cli#6]
Hi, 
When deploying html files, it seems empty attributes are removed once they land on aerobatic.

By empty attributes I mean something like the following :
```html
<div layout horizontal center-center fit>
   Main content
</div>
```

On aerobatic, I just have this 
```html
<divt>
   Main content
</div>
```
I've created a sample application https://github.com/plequang/aerobatic-test/blob/master/app/index.html.

Deployed version : http://aerobatic-test.aerobaticapp.com/

**Comment by dvonlehman** [comment]
This defect was resolved with a fix to the htmlprep module.
https://github.com/4front/htmlprep/commit/8e1b0a6fb640c4c795e7188bc19d42deaa569f6b
